// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteDengine;

#nullable disable

namespace Invoice.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoice.Business.Models.Fatura", b =>
                {
                    b.Property<int>("FaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaId"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.HasKey("FaturaId");

                    b.ToTable("Fatura", (string)null);
                });

            modelBuilder.Entity("Invoice.Business.Models.FaturaItem", b =>
                {
                    b.Property<int>("FaturaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaItemId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("FaturaId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ValorAprovado")
                        .HasColumnType("bit");

                    b.HasKey("FaturaItemId");

                    b.HasIndex("FaturaId");

                    b.ToTable("FaturaItem", (string)null);
                });

            modelBuilder.Entity("Invoice.Business.Models.FaturaItem", b =>
                {
                    b.HasOne("Invoice.Business.Models.Fatura", "Fatura")
                        .WithMany("FaturaItem")
                        .HasForeignKey("FaturaId")
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Invoice.Business.Models.Fatura", b =>
                {
                    b.Navigation("FaturaItem");
                });
#pragma warning restore 612, 618
        }
    }
}
